

from __future__ import annotations  # type or "|" operator is available since python 3.10 for lower python used this line
# lib imports
import numpy as np
import pandas as pd
from sktime.forecasting.base import BaseForecaster
from sklearn.metrics import r2_score
from utils import Solar
from utils.Plotter import Plotter
from matplotlib import pyplot as plt
from datetime import datetime as dt
from typing import List

import warnings


# Very general methods to be simplified in in this class. It is needed for lstm and cnn
#     def fit_generate_dimensions_and_make_dataset(
#         self,
#         train_ts: pd.DataFrame,
#         period: int,
#         predict_window_length,
#         target,
#         exogenous,
#     ) -> Tuple[pd.Series, pd.DataFrame]:
#         # train_ts_ex = self.chain.fit_transform(train_ts[target])
#         # train_ts_ex.rename(columns={"y": target})
#         # [fh:] and [:-fh] is needed to avoid look ahead. However, it is needed only in fit_(...)_dataset beacuse this
#         # function gets train_ts and transforms it into features and labels. predict_(...)_dataset gets predict_ts(X) and
#         # test_df (Y) separately. SWE ensres that those two sets do not overlap in time domain
#         x_ex = train_ts[exogenous]  # get exogenous parameters
#         lagged_target = train_ts.iloc[:-period][target]  # get exogenous parameters
#         train_ds_x = x_ex.merge(
#             lagged_target, how="outer", left_index=True, right_index=True
#         )
#         train_ds_y = train_ts[[target]].copy()  # y contains ground truth
#         # train_ds_x = train_ts.iloc[:-period] # it contains features generated by chain transform and y observations
#         return train_ds_y, train_ds_x.fillna(0)
#
#     # method to be overwritten
#     def predict_generate_dimensions_and_make_dataset(
#         self,
#         predict_ts: pd.DataFrame,
#         test_ts: pd.DataFrame,
#         period: int,
#         fh: int,
#         target,
#         exogenous,
#     ) -> Tuple[pd.Series, pd.DataFrame]:
#         # print("predict_ts.shape", predict_ts.shape, "self.predict_window_length_", self.predict_window_length_)
#
#         # if_current_sample_is
#         x_ex = test_ts[exogenous]
#         lagged_target = predict_ts.iloc[:-period][target]
#         test_ds_x = x_ex.merge(
#             lagged_target, how="outer", left_index=True, right_index=True
#         )
#         test_ds_y = test_ts[[target]].copy()  # y contains ground truth
#         # test_ds_y = test_ts.iloc[:fh] # test_df is a series containing ground truth len() == fh
#         # test_ds_x = test_ts_ex[-period:len(test_ts_ex)-period+len(test_ds_y)] # it contains features generated by chain transform and y observations
#
#         return test_ds_y, test_ds_x.fillna(0)

class NonTSModelWrapper(BaseForecaster):
    """This class implements model with different prediction method. Not iterative. """
    _tags = {
        "requires-fh-in-fit": False
    }

    def __init__(self, sklearn_model_constructor, n=None, n_step=None, dims=None, flatten_last_dim=False, **constructor_parameters):
        """

        sklearn_model_constructor: function that returns sklearn model or a tuple (sklearn model, model_name)

            dims: dimensions from X passed to the model. Available: x, y'
            flatten_last_dim: determinied if lagged input data should be flattened (samples, n, features) => (samples, n * features)
        """
        super().__init__()
        self.sklearn_model_constructor = sklearn_model_constructor
        self.constructor_parameters = constructor_parameters
        self.model = None
        self.model_name = "NonTSModelWrapper"
        self.period_in_samples=288
        self.n=n
        self.n_step=n_step
        self.flatten_last_dim=flatten_last_dim

        self.dims = dims

        if self.dims is not None:
            available = ["x", "y'"]
            error = []
            for d in self.dims:
                if d not in available:
                    error.append(f"selected dimension={d} is not in {available}")
            if error:
                error_str = '\n - '.join(error)
                raise RuntimeError(f"NonTSModelWrapper: Cannot construct\n - {error_str}")

        # used for prediction just after fit
        self._y = None

    def construct_model(self):
        self.model = self.sklearn_model_constructor(**self.constructor_parameters)

        if isinstance(self.model, tuple):
            self.model, self.model_name = self.model

        return self.model


    def call_select_model_dataset(
        self,
        train_ds_y: pd.Series,
        train_ds_x: pd.DataFrame,
        dims: List[str]=None,
        n: int = None,
        n_step: int = None,
    ) -> Tuple[np.array, np.array]:
        """
        Function limits already prepared learning dataset for each model separately using defined dimensions set (list)
        which is provided for each model in self.register_model. Moreover, function transforms pd.DataFrames into numpy arrays
        that can be consumed by sklearn native models. Method may be overwritten in case of trajectory forecasting.
        :param train_ds_y: call_fit_dataset first returned tuple element fitting labels set (Y)
        :param train_ds_x: call_fit_dataset second returned tuple element fitting features set (X)
        :param dims: list of columns in X (aka list of features) used by particlular model
        :param n: n tells the model how many days (window-size) shoudl describes test sets. If n is not none shape of returned
                  data changes into (samples, time, features) instead of (samples, features) which is a default behavior.
                  n is equals to shape[1] (len(time)) it can be either 1 or grater. If 1 it only reshapes dataset. n_step
                  parameter is closly connected with n. If n is > 1 then each time sample is lagged by n_steps e.g. n_steps=1 =>
                  time(n-1) = time(n) - 1, if n_steps=10 => time(n-10) = time(n) - 10 (time is counted in samples not time units(seconds, minutes etc.)
        :param n_step: see n argument description
        :return: Tuple of train_ds_y, train_ds_x containing limited number of columns (by model's dimensions)- prepared for current test iteration
        """
        # reduce dataset
        if (
            dims is None
        ):  # check if for selected model dimensions are defined. If so then adjust learning set
            ds_y, ds_x = (
                train_ds_y.values,
                train_ds_x.values,
            )  # 2D (samples, 1) or 1D (samples), 2D (samples, features)
        else:
            ds_y, ds_x = (
                train_ds_y.values,
                train_ds_x[dims].values,
            )  # 2D (samples, 1) or 1D (samples), 2D (samples, features)

        if len(ds_y.shape) == 1:
            ds_y = ds_y.reshape(-1, 1)  # ensure it is 2D

        if n is not None:
            # ds_y = np.stack([ds_y[i:(-n+i),:] for i in range(n)], axis=1) #3D (samples, n, 1) n=>time
            ds_x = np.stack(
                [ds_x[n*n_step - i*n_step:len(ds_x) - i*n_step] for i in range(n)], axis=1
            )  # 3D (samples, n, features) n=>time

        min_shape = min([ds_x.shape[0], ds_y.shape[0]])
        ds_y = ds_y[-min_shape:]
        ds_x = ds_x[-min_shape:]
        return ds_y, ds_x

    def make_x_fit(self, ts):
        """Function changes timeseries into observations: (timestep, power), where timestep
        divides day into 288 bins.

        function returns X,y for sklearn model
        """
        data = ts.to_frame().reset_index()
        data.rename(columns={"NormalizedPower":"y'"}, inplace=True)
        print(data)
        # print(len(data["y'"].iloc[:-self.period_in_samples] ), len(data["y'"].iloc[self.period_in_samples:]))
        data["y'"].iloc[:-self.period_in_samples] = data["y'"][self.period_in_samples:].values
        data["y'"].iloc[-self.period_in_samples:] = 0

        data["x"] = (data["timestamp"].dt.hour*60*60+ data["timestamp"].dt.minute*60+ data["timestamp"].dt.second) // 288
        return data[["x", "y'"]]

    def make_x_predict(self, ts):
        """Function changes timeseries into observations: (timestep, power), where timestep
        divides day into 288 bins.

        function returns X,y for sklearn model
        """
        data = ts.to_frame()
        data = data.reset_index()
        data["timestamp"] = (data["timestamp"].dt.hour * 60 * 60 + data["timestamp"].dt.minute * 60 + data[
            "timestamp"].dt.second) // 288
        data.rename(columns={
            "NormalizedPower": "y'",
            "timestamp": "x"
        }, inplace=True)

        return data

    def _fit(self, y, X=None, fh=None):
        self._y = y
        print("NonTSModelWrapper._fit:", y.shape)

        y_ds_fit, x_ds_fit = self.call_select_model_dataset(
            # make 1 period shift between X and y
            y,
            self.make_x_fit(y),
            dims=self.dims,
            n=self.n,
            n_step=self.n_step
        )

        # print(x_ds_fit)
        if len(x_ds_fit.shape) == 3 and self.flatten_last_dim:
            x_ds_fit = x_ds_fit.reshape(x_ds_fit.shape[0], -1)

        print("x_ds_fit:", x_ds_fit.shape, "y_ds_fit", y_ds_fit.shape)
        self.construct_model()

        self.model.fit(x_ds_fit, y_ds_fit)

    def _predict(self, fh, X):
        print("NonTSModelWrapper._predict:", X, fh)

        y = self._y
        _, x_ds = self.call_select_model_dataset(
            # make 1 period shift between X and y
            pd.Series(data=[]),
            self.make_x_predict(y),
            dims=self.dims,
            n=self.n,
            n_step=self.n_step
        )

        # x_ts = pd.DataFrame(data=x_ds, index=y.index[-len(x_ds):])



        # x = self._y[-self.period_in_samples]

        fh = fh.to_pandas().to_frame().reset_index(drop=True)
        fh["x"] = (fh["timestamp"].dt.hour * 60 * 60 + fh["timestamp"].dt.minute * 60 + fh["timestamp"].dt.second) // 288

        # x_ts maps index to timestamp
        # x_ts = pd.Series(data=x_ds[:,0,0], name="timestamp").to_frame().reset_index()
        if self.n is not None and self.n_step is not None:
            x_ts = pd.Series(data=self._y.index[self.n*self.n_step:], name="timestamp").to_frame().reset_index()
        else:
            x_ts = pd.Series(data=self._y.index, name="timestamp").to_frame().reset_index()

        print(" ==> x_ts")
        print(x_ts)

        print(" ==> fh")
        print(fh)
        fh["timestamp"] = fh["timestamp"] - pd.Timedelta(days=1)
        indexes = pd.merge(fh, x_ts, on="timestamp")["index"]

        # take selected indexes and remove timestamp dimension
        print(" ==> fh'")
        print(fh)
        print(" ==> indexes'")
        print(indexes)
        print("x_ds.shape", x_ds.shape)
        x_predict = x_ds[indexes].astype(np.float32)

        if len(x_predict.shape) == 3 and self.flatten_last_dim:
            x_predict = x_predict.reshape(x_predict.shape[0], -1)

        print("x_predict.shape", x_predict)
        return self.model.predict(x_predict)

    def __str__(self):
        return "NonTSModelWrapper (" + str(self.model_name) + ")"

    def plot(self):
        pass